// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

/**
 * @title IVerifier
 * @notice Interface for Noir ZK proof verifier
 * @dev This interface matches the Barretenberg-generated verifier contract
 * @author Waiola Team
 */
interface IVerifier {
    /**
     * @notice Verify a ZK proof
     * @param _proof The proof bytes (generated by Noir prover)
     * @param _publicInputs Array of public inputs (as bytes32)
     * @return True if proof is valid, false otherwise
     *
     * Public inputs for RFQ Quote circuit (in order):
     * [0] commitment    - Quote commitment hash
     * [1] poolKeyHash   - Hash of PoolKey
     * [2] taker         - Taker address (as bytes32)
     * [3] amountIn      - Input amount
     * [4] minOut        - Minimum output (slippage protection)
     * [5] expiry        - Quote expiry timestamp
     */
    function verify(
        bytes calldata _proof,
        bytes32[] calldata _publicInputs
    ) external view returns (bool);
}
